### ISSUE TITLE
Revision not supported...

### ISSUE THREAD

**Issue by Criptos** [tolga9009/elgato-gchd#26] opened 2016-09-08 23:43 UTC
Driver downloaded: 
gchdm_204_981.dmg

Firmware: 
[root@strix gchd]# pwd
/usr/lib/firmware/gchd
[root@strix gchd]# ls
mb86h57_h58_enc_h.bin  mb86h57_h58_idle.bin

[root@strix build]# ./Project -r 1080 
FIFO: /tmp/gchd.ts has been created.
Waiting for user to open it.
This revision of the Elgato Game Capture HD is currently not supported.

Is this just a driver issue? Where to donwload the driver with the correct device.
If not?, well, when do we setup a vpn so you can access the hardware? or any advice to support it is welcome

**Comment by tolga9009** [comment] 2016-09-08 23:55
Hi there,

I assume you have the Elgato Game Capture HD (not HD60 / HD60 Pro / HD60 S)? Please check with the command `lsusb`, which PID your device has. If it's 0x005d, then I'm sorry. There is currently no support for that revision. We have an issue tracker in #12.

Cheers,
Tolga

**Comment by Criptos** [comment] 2016-09-09 01:25
Yes, I have it. :(

**Comment by tolga9009** [comment] 2016-09-09 03:08
Okay, I'm marking this as a duplicate of #12 then. We can discuss details there.

**Closed by tolga9009** 2016-09-09 03:08 UTC
Labels: duplicate
